import { type ActionFunctionArgs, type LoaderFunctionArgs, json } from '@remix-run/cloudflare';

/**
 * Server-side sandbox proxy (E2B).
 *
 * Runs AI-generated projects in a managed cloud sandbox — full `npm install` +
 * dev server — and returns a public preview URL. This is the reliable
 * execution tier for mobile Safari, where the in-browser WebContainer cannot
 * run real dev servers.
 *
 * The E2B API key lives only here (Cloudflare env `E2B_API_KEY`) and is never
 * exposed to the browser. The client talks to this route via /api/sandbox.
 *
 * IMPORTANT: The `e2b` SDK is imported DYNAMICALLY (inside action handlers),
 * not at the module level. The SDK depends on Node.js internals (WebSocket,
 * crypto, buffer) that may not all be polyfilled in Cloudflare Workers. A
 * static top-level import would crash the entire route module on load, making
 * even the GET health check fail. By deferring the import, the loader stays
 * healthy and can report `configured: true` while only the sandbox operations
 * fail gracefully if the SDK truly can't load.
 */

const PROJECT_DIR = '/home/user/project';
const DEFAULT_PORT = 3000;
const SANDBOX_TIMEOUT_MS = 1000 * 60 * 7; // auto-close after 7 min idle (cost control)

function getApiKey(context: ActionFunctionArgs['context']): string | undefined {
  const env = (context as unknown as { cloudflare?: { env?: Record<string, string> } }).cloudflare?.env;

  const key = env?.E2B_API_KEY;

  if (key) {
    console.log('[api/sandbox] E2B_API_KEY found in cloudflare env');
  } else {
    console.warn('[api/sandbox] E2B_API_KEY is NOT set in cloudflare env');
  }

  return key || (typeof process !== 'undefined' ? process.env?.E2B_API_KEY : undefined);
}

// GET /api/sandbox — health/config check
export async function loader({ context }: LoaderFunctionArgs) {
  const hasKey = Boolean(getApiKey(context));
  console.log(`[api/sandbox] health check: configured=${hasKey}`);

  return json({ ok: true, configured: hasKey });
}

interface SandboxRequest {
  op: 'create' | 'files' | 'start' | 'status' | 'logs' | 'destroy';
  id?: string;
  files?: Record<string, string>;
  install?: string;
  dev?: string;
  port?: number;
}

export async function action({ context, request }: ActionFunctionArgs) {
  const apiKey = getApiKey(context);

  if (!apiKey) {
    return json({ error: 'E2B_API_KEY is not configured on the server' }, { status: 501 });
  }

  let body: SandboxRequest;

  try {
    body = (await request.json()) as SandboxRequest;
  } catch {
    return json({ error: 'invalid JSON body' }, { status: 400 });
  }

  try {
    switch (body.op) {
      case 'create': {
        /*
         * Dynamic import — isolated to this code path so a failure here
         * doesn't crash the GET loader.
         */
        const { Sandbox: sandboxClass } = await import('e2b');
        const sandbox = await sandboxClass.create({ apiKey, timeoutMs: SANDBOX_TIMEOUT_MS });

        console.log(`[api/sandbox] created sandbox: ${sandbox.sandboxId}`);

        return json({ id: sandbox.sandboxId });
      }

      case 'files': {
        if (!body.id || !body.files) {
          return json({ error: 'id and files are required' }, { status: 400 });
        }

        const { Sandbox: sandboxClass } = await import('e2b');
        const sandbox = await sandboxClass.connect(body.id, { apiKey });

        for (const [path, content] of Object.entries(body.files)) {
          const clean = path.replace(/^\/+/, '');
          await sandbox.files.write(`${PROJECT_DIR}/${clean}`, content);
        }

        return json({ ok: true, count: Object.keys(body.files).length });
      }

      case 'start': {
        if (!body.id) {
          return json({ error: 'id is required' }, { status: 400 });
        }

        const { Sandbox: sandboxClass } = await import('e2b');
        const sandbox = await sandboxClass.connect(body.id, { apiKey });
        const port = body.port ?? DEFAULT_PORT;
        const install = body.install ?? 'npm install --no-audit --no-fund';
        const dev = body.dev ?? `npm run dev -- --host 0.0.0.0 --port ${port} --base=/preview/`;

        /*
         * Vite 5+ blocks requests whose Host is unknown (the e2b.app host), which
         * breaks the same-origin preview proxy. Inject `server.allowedHosts: true`
         * into the vite config (create a minimal one if none exists) so the proxy
         * can reach it. Covers the common `defineConfig({ ... })` / `export default
         * { ... }` shapes generated by the model.
         *
         * We also set `server.hmr.host` and `server.hmr.clientPort` so the Vite
         * HMR client in the iframe tries to reach the WebSocket on the SAME origin
         * (palmkit.app) instead of the sandbox host. The reverse proxy in
         * functions/preview/[[path]].ts forwards WebSocket upgrade requests to
         * the sandbox, keeping live-reload working through COEP.
         */
        const patchHosts =
          `if ls vite.config.* >/dev/null 2>&1; then ` +
          `sed -ri 's/defineConfig\\(\\{/defineConfig({server:{allowedHosts:true,host:true,hmr:{host:\"palmkit.app\",protocol:\"wss\",clientPort:443}},/; ` +
          `s/export default \\{/export default {server:{allowedHosts:true,host:true,hmr:{host:\"palmkit.app\",protocol:\"wss\",clientPort:443}},/' vite.config.* 2>/dev/null || true; ` +
          `else echo "export default { server: { allowedHosts: true, host: true, hmr: { host: 'palmkit.app', protocol: 'wss', clientPort: 443 } } }" > vite.config.js; fi`;

        /*
         * Keep the sandbox alive while the dev server runs, then patch hosts +
         * install + run the dev server in the background so this returns fast.
         */
        await sandbox.setTimeout(SANDBOX_TIMEOUT_MS);
        await sandbox.commands.run(`cd ${PROJECT_DIR} && (${patchHosts}; ${install} && ${dev}) > /tmp/dev.log 2>&1`, {
          background: true,
        });

        const host = sandbox.getHost(port);
        console.log(`[api/sandbox] sandbox ${body.id} started, preview at https://${host}`);

        return json({ url: `https://${host}`, port });
      }

      case 'logs': {
        if (!body.id) {
          return json({ error: 'id is required' }, { status: 400 });
        }

        const { Sandbox: sandboxClass } = await import('e2b');
        const sandbox = await sandboxClass.connect(body.id, { apiKey });
        const out = await sandbox.commands
          .run('tail -n 60 /tmp/dev.log 2>/dev/null || echo "(no logs yet)"', { timeoutMs: 8000 })
          .catch(() => ({ stdout: '(logs unavailable)' }) as { stdout: string });

        return json({ logs: out.stdout || '' });
      }

      case 'status': {
        if (!body.id) {
          return json({ error: 'id is required' }, { status: 400 });
        }

        const port = body.port ?? DEFAULT_PORT;

        /*
         * Probe the PUBLIC e2b host on the real preview path — exactly what the
         * iframe will load. This (unlike an inside-the-sandbox localhost curl)
         * verifies the dev server is reachable externally (bound to 0.0.0.0) AND
         * serves /preview/, so we never show the iframe while it would 502/404.
         */
        let code = 0;

        try {
          const probe = await fetch(`https://${port}-${body.id}.e2b.app/preview/`, {
            method: 'GET',
            redirect: 'manual',
          });
          code = probe.status;
        } catch {
          code = 0;
        }

        const ready = code >= 200 && code < 400;

        return json({ ready, code });
      }

      case 'destroy': {
        if (!body.id) {
          return json({ error: 'id is required' }, { status: 400 });
        }

        const { Sandbox: sandboxClass } = await import('e2b');
        const sandbox = await sandboxClass.connect(body.id, { apiKey });
        await sandbox.kill();

        console.log(`[api/sandbox] destroyed sandbox: ${body.id}`);

        return json({ ok: true });
      }

      default:
        return json({ error: `unknown op: ${String(body.op)}` }, { status: 400 });
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    console.error(`[api/sandbox] operation ${body.op} failed:`, message);

    return json({ error: message }, { status: 500 });
  }
}
